version: "3"
services:
  node9:
    image: node:9
    working_dir: /home/node/app
    # environment:
      # - NODE_ENV=production
    ports:
      - "8089:1337"
    volumes:
      - ./:/home/node/app/
    command: "npm start"
  node8:
    image: node:8
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - "8088:1337"
    volumes:
      - ./:/home/node/app/
    command: "npm start"
  node7:
    image: node:7
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - "8087:1337"
    volumes:
      - ./:/home/node/app/
    command: "npm start"